urls.py
from .import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    path("index/",views.IndexClassView.as_view(),name="index"),
    path("it/",views.it,name="it"),
    path("<int:pk>/",views.FoodDetail.as_view(),name="detail"),
    path("add/",views.createitem.as_view(),name="create_form"),
    path("update/<int:pk>/",views.updateitem.as_view(),name='update_item'),
    path("delete/<int:id>/",views.delete_item,name="delete_item"),
    ]

forms.py
from django import forms
from .models import item

class itemform(forms.ModelForm):
    class Meta:
        model=item
        fields=['item_name', 'item_desc', 'item_price', 'item_image']

views.py
from django.http import HttpResponse
from .models import item
from django.template import loader
from django.shortcuts import render , redirect
from .forms import itemform
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.urls import reverse, reverse_lazy




# def index(request):
#     item_list = item.objects.all()
#     context={ 'item_list':item_list,
 
       
#     }
#     return render(request,"food/index.html",context)

class IndexClassView(ListView):
    model=item
    template_name='food/index.html'
    context_object_name='item_list'

def it(request):
    return HttpResponse("<h1>This is an item view<h1>")

# def detail(request,item_id):
#     shi=item.objects.get(pk=item_id)
#     context={'shi':shi,
             
#     }
#     return render(request,"food/detail.html",context)

class FoodDetail(DetailView):
    model=item
    template_name='food/detail.html'
   

# def create_form(request):
#     qwer=itemform(request.POST or None)
#     if qwer.is_valid():
#         qwer.save()
#         return redirect('food:index')
    
#     return render(request,'food/item-form.html',{'qwer':qwer,})
class createitem(CreateView):
    model=item
    form_class=itemform
    context_object_name='form'
    

    template_name='food/item-form.html'
    # success_url= reverse_lazy('food:index')
    
    
    def form_valid(self,form):
        form.instance.user_name=self.request.user
        
        return super().form_valid(form)

# def update_item(request,id):
#     pq=item.objects.get(id=id)
#     qwer=itemform(request.POST or None, instance=pq)
#     if qwer.is_valid():
#         qwer.save()
#         return redirect('food:index')
#     return render(request,'food/item-form.html',{'pq':pq,'qwer':qwer})

class updateitem(UpdateView):
    model=item
    form_class=itemform
    template_name='food/item-form.html'

    def form_valid(self,form):
        return super().form_valid(form)

def delete_item(request,id):
    pq=item.objects.get(pk=id)
    if request.method=="POST":
        pq.delete()
        return redirect('food:index')
    return render(request,'food/delete-item.html',{'pq':pq})
    


        

templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark  bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>
       <div class="navbar">
            <a class="nav-item nav-link", href="{% url 'food:create_form'%}">Add Item</a> 
            <a class="nav-item nav-link", href="#">Delete Item</a> 
            <a class="nav-item nav-link", href="#">View Item</a> 
            {% if user.is_authenticated %}
                <a href="{% url 'Logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'Login' %}">Login</a>  
            {% endif %}      
        </div>
    </nav>
    {% if messages %}
       {% for message in messages %}
           <div class="alert alert-{{message.tag}}">{{message}}</div>
       {% endfor %}
    {% endif %}      
    {% block body %}
    {% endblock %}
    
</body>
</html>

templates/food/delete-item.html
{% extends 'food/base.html' %}

{% block body %}
<form type="POST">
    <h3>Are you sure you want to delete {{pq.item_name}}</h3>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" height="300px" src="{{object.item_image}}">
        </div>
        <div class="col-md-4">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>${{object.item_price}}</h3>

       <div class="col-md-2">
            <a href="{% url 'food:update_item' object.id %}" class="btn btn-success">Edit</a>
            <br>
            <br>
            <br>
            <a href="{% url 'food:delete_item' object.id %}" class="btn btn-success">Delete</a>
        </div>    
      
        
          
        </div>
    </div>
</div>
    
{% endblock %}

templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    {% block body %}

    {% for item in item_list %}
    <br>
        <div class="row" >
            <div class="col-md-3 offset-md-2">
                <img class="card" height="180px" width="300px" src="{{item.item_image}}">

            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>${{item.item_price}}</h6>

            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.pk %}" class="btn btn-success">Details</a>

            </div>

        </div>
    
    {% endfor %}

    {% endblock %}


   
</body>
</html>

templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
       {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}